scripts/unifdef: avoid constexpr keyword
Starting with c23, 'constexpr' is a keyword in C like in C++ and cannot
be used as an identifier:

ernel/xiaomi/sm8450/scripts/unifdef.c:206:25: error: 'constexpr' can only be used in variable declarations
  206 | static bool             constexpr;              /* constant #if expression */
      |                         ^
kernel/xiaomi/sm8450/scripts/unifdef.c:880:13: error: expected identifier or '('
  880 |                 constexpr = false;
      |                           ^
kernel/xiaomi/sm8450/scripts/unifdef.c:898:13: error: expected identifier or '('
  898 |                 constexpr = false;
      |                           ^
kernel/xiaomi/sm8450/scripts/unifdef.c:958:12: error: expected identifier or '('
  958 |         constexpr = killconsts ? false : true;
      |                   ^
kernel/xiaomi/sm8450/scripts/unifdef.c:961:10: error: expected expression
  961 |         return (constexpr ? LT_IF : ret == LT_ERROR ? LT_IF : ret);

Rename this instance to allow changing to C23.

Signed-off-by: klozz <carlosj@klozz.dev>